# Generated by Django 4.1.7 on 2023-06-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_branch_name_alter_city_delivery_cost_and_more'),
        ('store', '0002_alter_item_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='account.branch'),
        ),
    ]
